name: Deploy Storybooks

on:
  push:
    branches:
      - sb

jobs:
  build-and-deploy:
    if: github.head_ref != 'dev' && github.head_ref != 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpx nx run micro-ui:build-storybook --skip-nx-cache

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: apps/micro-ui/storybook-static
          destination_dir: sb/main
          keep_files: true
