name: Deploy Storybooks

on:
  push:
    branches:
      - main-sb
      - dev-sb

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: |
          if [ "${{ github.ref_name }}" == "main-sb" ]; then
            pnpx nx run micro-ui:build-storybook --output-dir=storybook-static/micro-ui/main --skip-nx-cache
          elif [ "${{ github.ref_name }}" == "dev-sb" ]; then
            pnpx nx run micro-ui:build-storybook --output-dir=storybook-static/micro-ui/dev --skip-nx-cache
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: apps/micro-ui/storybook-static
          keep_files: true
