name: Deploy Storybook Preview

on:
  pull_request:
    branches:
      - sb
    types: [opened, synchronize, reopened]

jobs:
  deploy-storybook:
    if: github.head_ref != 'dev' && github.head_ref != 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpx nx run micro-ui:build-storybook --skip-nx-cache

      - name: Deploy to Temporary Folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: apps/micro-ui/storybook-static
          destination_dir: sb/pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Add Storybook Preview Link to PR Description
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          STORYBOOK_URL="https://chaddoy.github.io/fs/sb/pr-${{ github.event.pull_request.number }}"
          PR_BODY="### Storybook Preview\n\nView the Storybook preview here: [Storybook Preview](${STORYBOOK_URL})\n\n$(
            curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}" \
            | jq -r .body
          )"

          curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"$PR_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"
